### ISSUE TITLE
Wait Time/Possible Crash Happening Sometimes

### ISSUE THREAD

**Issue by Cooldude9210** [NeighNeighNeigh/Alfred_IconGenerator#2]
I don't know 100% why, but occasionally, when trying to use the workflow to alter the foreground color, the workflow never shows the color swatches. Looking at the debugger, it shows it pulling the swatch icons from the Workflow Data folder, but it never seems to proceed to the "Processing Complete" step.

**Comment by NeighNeighNeigh** [comment]
Hey @Cooldude9210 thanks for reaching out. I think I fixed the issue, would you mind trying out the 3.3 prerelease and let me know if you have any issues? https://github.com/NeighNeighNeigh/Alfred_IconGenerator/releases/tag/v3.3Prerelease

**Comment by NeighNeighNeigh** [comment]
Fixed in 3.3. Closing this issue, but if you have any continued problem with this issue, please feel free to reopen.
